version: '3.8'

networks:
  local-kafka:
    driver: bridge

volumes:
  kafka-data:


services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - local-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    volumes:
      - ./logs/zookeeper:/var/log/zookeeper
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    networks:
      - local-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_C://0.0.0.0:9093,PLAINTEXT_L://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_L://localhost:9092,PLAINTEXT_C://broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_L:PLAINTEXT,PLAINTEXT_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

    volumes:
      - ./logs/broker:/var/log/broker
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"



  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - local-kafka
    depends_on: 
      - broker
    ports:
      - "7777:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

    volumes:
      - ./logs/kafka-ui:/var/log/kafka-ui
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  producer1:
    build:
      context: ./docker/producer
    container_name: whereismydad-producer1

    depends_on:
      - broker
    networks:
      - local-kafka
    working_dir: /app
    command: python producer.py
    environment:
      KAFKA_SERVER: broker:9092
      PRODUCER_ID: producer1
      KAFKA_TOPIC: topic_test
    volumes:
      - ./docker/producer/app:/app
      - ./logs/producers/producer1:/var/log/producer1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  producer2:
    build:
      context: ./docker/producer
    container_name: whereismydad-producer2
    depends_on:
      - broker
    networks:
      - local-kafka
    working_dir: /app
    command: python producer.py
    environment:
      PRODUCER_ID: producer2
      KAFKA_SERVER: broker:9092
      KAFKA_TOPIC: topic_test
    volumes:
      - ./docker/producer/app:/app
      - ./logs/producers/producer2:/var/log/producer2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"



  consumer:
    build:
      context: ./docker/consumer
    container_name: whereismydad-consumer
    depends_on:
      - broker
    networks:
      - local-kafka
    volumes:
      - ./docker/consumer/app:/app
      - ./logs/consumer:/var/log/consumer
    working_dir: /app
    command: python consumer.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

