services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_consumer
    working_dir: /app
    volumes:
      - .:/app  # Monte le répertoire actuel dans /app dans le conteneur
    command: >
      bash -c "pip install kafka-python && python -u consumer.py"
    ports:
      - "8080:8080"  # Si tu souhaites exposer le port pour Kafka (optionnel)
    environment:
      - PYTHONUNBUFFERED=1  # Pour assurer un affichage en temps réel des logs
