CREATE TABLE IF NOT EXISTS gps_messages (
    id SERIAL PRIMARY KEY,
    daddy_id INTEGER NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);